spring:
  application:
    name: mesh-talk-common-cache

  redis:
    database: 0
    host: 117.72.33.162
    port: 16379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    address: redis://117.72.33.162:16379

local:
  cache:
    type: guava

distribute:
  lock:
    type: redisson
  cache:
    type: redis

redis:
  arrange:
    type: single # single or cluster

message:
  mq:
    type: rocketmq